uri: project://config
name: Configuration Files
description: Configuration files discovery
mimeType: application/json
handler:
  module: python_package_mcp_server.resources.project_index
  function: read_project_index_resource
uriTemplate: project://config
